/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LegislativeNotary } from "./LegislativeNotary";
export * as factories from "./factories";
export { LegislativeNotary__factory } from "./factories/LegislativeNotary__factory";
