/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LegislativeNotaryInterface extends Interface {
  getFunction(
    nameOrSignature: "orchestratorAdmin" | "proclaimRound" | "rounds"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RoundProclaimed"): EventFragment;

  encodeFunctionData(
    functionFragment: "orchestratorAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proclaimRound",
    values: [string, string, boolean, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "rounds", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "orchestratorAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proclaimRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
}

export namespace RoundProclaimedEvent {
  export type InputTuple = [
    roundId: string,
    isNominal: boolean,
    nominalRoot: BytesLike,
    tallyRoot: BytesLike,
    eligibilityRoot: BytesLike,
    agendaItemTitle: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    roundId: string,
    isNominal: boolean,
    nominalRoot: string,
    tallyRoot: string,
    eligibilityRoot: string,
    agendaItemTitle: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    roundId: string;
    isNominal: boolean;
    nominalRoot: string;
    tallyRoot: string;
    eligibilityRoot: string;
    agendaItemTitle: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegislativeNotary extends BaseContract {
  connect(runner?: ContractRunner | null): LegislativeNotary;
  waitForDeployment(): Promise<this>;

  interface: LegislativeNotaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  orchestratorAdmin: TypedContractMethod<[], [string], "view">;

  proclaimRound: TypedContractMethod<
    [
      _roundId: string,
      _title: string,
      _isNominal: boolean,
      _nominalRoot: BytesLike,
      _tallyRoot: BytesLike,
      _eligibilityRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  rounds: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean, boolean] & {
        nominalMerkleRoot: string;
        tallyMerkleRoot: string;
        eligibilityMerkleRoot: string;
        timestamp: bigint;
        isNominal: boolean;
        isProclaimed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "orchestratorAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proclaimRound"
  ): TypedContractMethod<
    [
      _roundId: string,
      _title: string,
      _isNominal: boolean,
      _nominalRoot: BytesLike,
      _tallyRoot: BytesLike,
      _eligibilityRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean, boolean] & {
        nominalMerkleRoot: string;
        tallyMerkleRoot: string;
        eligibilityMerkleRoot: string;
        timestamp: bigint;
        isNominal: boolean;
        isProclaimed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RoundProclaimed"
  ): TypedContractEvent<
    RoundProclaimedEvent.InputTuple,
    RoundProclaimedEvent.OutputTuple,
    RoundProclaimedEvent.OutputObject
  >;

  filters: {
    "RoundProclaimed(string,bool,bytes32,bytes32,bytes32,string,uint256)": TypedContractEvent<
      RoundProclaimedEvent.InputTuple,
      RoundProclaimedEvent.OutputTuple,
      RoundProclaimedEvent.OutputObject
    >;
    RoundProclaimed: TypedContractEvent<
      RoundProclaimedEvent.InputTuple,
      RoundProclaimedEvent.OutputTuple,
      RoundProclaimedEvent.OutputObject
    >;
  };
}
