"""initial_migration

Revision ID: 1a30e7935895
Revises: 
Create Date: 2026-05-07 22:46:06.812053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a30e7935895'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislative_sessions',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'CLOSED', name='legislative_session_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('ephemeral_public_key', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislative_sessions'))
    )
    op.create_table('legislators',
    sa.Column('national_id', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('current_public_key', sa.Text(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislators')),
    sa.UniqueConstraint('current_public_key', name=op.f('uq_legislators_current_public_key')),
    sa.UniqueConstraint('national_id', name=op.f('uq_legislators_national_id'))
    )
    op.create_table('system_users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PRESIDENCY', 'AUDITOR', name='system_user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_users'))
    )
    op.create_index('uq_system_users_username_lower', 'system_users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('devices',
    sa.Column('legislator_id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.Text(), nullable=False),
    sa.Column('device_token', sa.Text(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_devices_legislator_id_legislators')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('device_token', name=op.f('uq_devices_device_token')),
    sa.UniqueConstraint('legislator_id', name=op.f('uq_devices_legislator_id')),
    sa.UniqueConstraint('mac_address', name=op.f('uq_devices_mac_address'))
    )
    op.create_table('motions',
    sa.Column('legislative_session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('is_nominal', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VOTING_OPEN', 'VOTING_CLOSED', 'RESOLVED', 'ABORTED', name='motion_status'), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['legislative_session_id'], ['legislative_sessions.id'], name=op.f('fk_motions_legislative_session_id_legislative_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_motions'))
    )
    op.create_index('idx_motions_session_id', 'motions', ['legislative_session_id'], unique=False)
    op.create_table('system_users_sessions',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['system_users.id'], name=op.f('fk_system_users_sessions_user_id_system_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_system_users_sessions'))
    )
    op.create_table('nominal_votes',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('motion_id', sa.UUID(), nullable=False),
    sa.Column('legislator_id', sa.UUID(), nullable=False),
    sa.Column('vote_value', sa.Enum('AFFIRMATIVE', 'NEGATIVE', 'ABSTENTION', name='nominal_vote_value'), nullable=False),
    sa.Column('cryptographic_signature', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_nominal_votes_legislator_id_legislators')),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], name=op.f('fk_nominal_votes_motion_id_motions')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_nominal_votes')),
    sa.UniqueConstraint('motion_id', 'legislator_id', name='uq_nominal_votes_motion_legislator')
    )
    op.create_table('non_nominal_votes',
    sa.Column('event_id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('motion_id', sa.UUID(), nullable=False),
    sa.Column('legislator_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('cryptographic_signature', sa.Text(), nullable=False),
    sa.Column('is_voided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name=op.f('fk_non_nominal_votes_legislator_id_legislators')),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], name=op.f('fk_non_nominal_votes_motion_id_motions')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_non_nominal_votes')),
    sa.UniqueConstraint('motion_id', 'legislator_id', name='uq_non_nominal_votes_motion_legislator')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('non_nominal_votes')
    op.drop_table('nominal_votes')
    op.drop_table('system_users_sessions')
    op.drop_index('idx_motions_session_id', table_name='motions')
    op.drop_table('motions')
    op.drop_table('devices')
    op.drop_index('uq_system_users_username_lower', table_name='system_users')
    op.drop_table('system_users')
    op.drop_table('legislators')
    op.drop_table('legislative_sessions')
    # ### end Alembic commands ###
